#!/bin/sh
set -e

cd ~/.config/nvim/.vim_runtime

echo '" DO NOT EDIT THIS FILE
" Add your own customizations in ~/.config/nvim/.vim_runtime/my_configs.vim

set runtimepath+=~/.vim_runtime

source ~/.config/nvim/.vim_runtime/vimrcs/basic.vim
source ~/.config/nvim/.vim_runtime/vimrcs/filetypes.vim
source ~/.config/nvim/.vim_runtime/vimrcs/plugins_config.vim
source ~/.config/nvim/.vim_runtime/vimrcs/extended.vim
try
  source ~/.config/nvim/.vim_runtime/my_configs.vim
catch
endtry' > ~/.config/nvim/init.vim

echo "Installed the Ultimate nvim configuration successfully! Enjoy :-)"
